import React, { useState } from 'react';
import { ProjectItem } from '../types';
import { playBeep, playKeyClick, playSuccessChime } from '../utils/audio';

interface SubdomainMatrixProps {
  projects: ProjectItem[];
  onAddProject: (project: ProjectItem) => void;
  onLaunchProject: (project: ProjectItem) => void;
  accentColorClass: string;
}

export const SubdomainMatrix: React.FC<SubdomainMatrixProps> = ({
  projects,
  onAddProject,
  onLaunchProject,
  accentColorClass,
}) => {
  const [showAddModal, setShowAddModal] = useState(false);
  const [newName, setNewName] = useState('');
  const [newSubdomain, setNewSubdomain] = useState('');
  const [newDescription, setNewDescription] = useState('');
  const [newTech, setNewTech] = useState('Astro, Tailwind, TypeScript');
  const [newGithub, setNewGithub] = useState('https://github.com/yourname/new-app');

  const [testingAll, setTestingAll] = useState(false);
  const [statuses, setStatuses] = useState<Record<string, { latency: string; status: string }>>({});

  // Interactive Namecheap DNS Generator state
  const [userDomain, setUserDomain] = useState('huon.si');
  const [targetPlatform, setTargetPlatform] = useState<'vercel' | 'github_pages'>('vercel');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const handleTestAll = () => {
    playBeep(520, 0.08);
    setTestingAll(true);
    setTimeout(() => {
      const update: Record<string, { latency: string; status: string }> = {};
      projects.forEach((p) => {
        update[p.id] = {
          latency: `${Math.floor(10 + Math.random() * 20)}ms`,
          status: '200 OK',
        };
      });
      setStatuses(update);
      setTestingAll(false);
      playSuccessChime();
    }, 600);
  };

  const handleAddSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newName.trim() || !newSubdomain.trim()) return;

    playSuccessChime();
    const id = newName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    const cleanSubdomain = newSubdomain.includes('.') ? newSubdomain : `${newSubdomain}.${userDomain}`;

    const newProj: ProjectItem = {
      id,
      name: newName.trim(),
      description: newDescription.trim() || 'A new edge micro-app hosted on a custom subdomain.',
      url: `https://${cleanSubdomain}`,
      subdomain: cleanSubdomain,
      github: newGithub.trim(),
      tech: newTech.split(',').map((t) => t.trim()).filter(Boolean),
      status: 'ONLINE',
      latency: '15ms',
      category: 'Micro-App',
      version: 'v1.0.0',
      demoType: 'telemetry',
    };

    onAddProject(newProj);
    setShowAddModal(false);
    setNewName('');
    setNewSubdomain('');
    setNewDescription('');
  };

  const handleCopyRecord = (key: string, text: string) => {
    playKeyClick();
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    playSuccessChime();
    setTimeout(() => setCopiedKey(null), 1500);
  };

  const cleanDomain = userDomain.trim().replace(/^https?:\/\//, '').replace(/\/$/, '') || 'huon.si';

  const exportZoneFile = () => {
    playKeyClick();
    const zoneLines = [
      `; ZONE FILE: ${cleanDomain}`,
      `; Generated by Terminal Portfolio Hub`,
      `$ORIGIN ${cleanDomain}.`,
      `$TTL 300`,
      targetPlatform === 'vercel'
        ? `@   IN  A   76.76.21.21 ; Vercel Apex`
        : `@   IN  A   185.199.108.153 ; GitHub Pages\n@   IN  A   185.199.109.153\n@   IN  A   185.199.110.153\n@   IN  A   185.199.111.153`,
      `www IN  CNAME ${targetPlatform === 'vercel' ? 'cname.vercel-dns.com.' : `${cleanDomain}.`}`,
      '',
    ];
    projects.forEach((p) => {
      const sub = p.subdomain.split('.')[0];
      zoneLines.push(`${sub.padEnd(16)} IN  CNAME ${targetPlatform === 'vercel' ? 'cname.vercel-dns.com.' : 'cname.vercel-dns.com.'} ; ${p.name}`);
    });

    const blob = new Blob([zoneLines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${cleanDomain}-namecheap-zone.txt`;
    a.click();
    URL.revokeObjectURL(url);
    playSuccessChime();
  };

  // Generate Namecheap records for the table
  const dnsRecords = [
    ...(targetPlatform === 'vercel'
      ? [
          { type: 'A Record', host: '@', value: '76.76.21.21', note: 'Vercel Apex Root IP' },
          { type: 'CNAME Record', host: 'www', value: 'cname.vercel-dns.com.', note: 'Vercel WWW alias' },
        ]
      : [
          { type: 'A Record', host: '@', value: '185.199.108.153', note: 'GitHub Pages IP 1' },
          { type: 'A Record', host: '@', value: '185.199.109.153', note: 'GitHub Pages IP 2' },
          { type: 'A Record', host: '@', value: '185.199.110.153', note: 'GitHub Pages IP 3' },
          { type: 'A Record', host: '@', value: '185.199.111.153', note: 'GitHub Pages IP 4' },
          { type: 'CNAME Record', host: 'www', value: `${cleanDomain}.`, note: 'GitHub Pages WWW alias' },
        ]),
    ...projects.map((p) => {
      const sub = p.subdomain.split('.')[0];
      return {
        type: 'CNAME Record',
        host: sub,
        value: 'cname.vercel-dns.com.',
        note: `${p.name} micro-app`,
      };
    }),
  ];

  return (
    <div className="space-y-8">
      {/* Namecheap Custom Domain Setup Generator */}
      <section className="border-2 border-[#1a3d1e] bg-[#091109] p-5 sm:p-6 space-y-5">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#1a331c] pb-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] text-[#00ff41] bg-[#142916] px-2 py-0.5 font-bold border border-[#1a3d1e]">
                NAMECHEAP DNS WIZARD
              </span>
              <span className="text-xs opacity-60">Step-by-step Domain Integration</span>
            </div>
            <h2 className={`text-base sm:text-lg font-bold mt-1 ${accentColorClass}`}>
              Connect Your Namecheap Domain
            </h2>
            <p className="text-xs opacity-80 mt-1 max-w-2xl leading-relaxed">
              Enter your Namecheap registered domain below to generate the exact DNS entries you must add
              under Namecheap&apos;s <strong>Advanced DNS</strong> settings.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs opacity-75">Target Platform:</span>
            <div className="flex border border-[#1a3d1e] bg-[#0c140c] p-1 text-xs">
              <button
                onClick={() => {
                  playKeyClick();
                  setTargetPlatform('vercel');
                }}
                className={`px-3 py-1 transition-colors ${
                  targetPlatform === 'vercel'
                    ? 'bg-[#142916] text-[#00ff41] font-bold border border-[#1a3d1e]'
                    : 'opacity-60 hover:opacity-100'
                }`}
              >
                Vercel (Recommended)
              </button>
              <button
                onClick={() => {
                  playKeyClick();
                  setTargetPlatform('github_pages');
                }}
                className={`px-3 py-1 transition-colors ${
                  targetPlatform === 'github_pages'
                    ? 'bg-[#142916] text-[#00ff41] font-bold border border-[#1a3d1e]'
                    : 'opacity-60 hover:opacity-100'
                }`}
              >
                GitHub Pages
              </button>
            </div>
          </div>
        </div>

        {/* Input Bar */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
          <label className="text-xs opacity-80 shrink-0">Your Registered Domain:</label>
          <div className="flex-1 flex items-center bg-[#070c07] border border-[#1a3d1e] px-3 py-1.5">
            <span className="text-xs opacity-50 mr-2">https://</span>
            <input
              type="text"
              value={userDomain}
              onChange={(e) => setUserDomain(e.target.value)}
              placeholder="e.g. huon.si"
              className="bg-transparent text-xs text-[#00ff41] font-mono outline-none flex-1 placeholder:opacity-40"
            />
          </div>
          <button
            onClick={exportZoneFile}
            className="px-4 py-2 border border-[#1a3d1e] hover:border-[#00ff41] text-xs font-mono transition-colors shrink-0"
          >
            Download Namecheap Zone File
          </button>
        </div>

        {/* Instructions for Namecheap UI */}
        <div className="bg-black/50 border border-[#142616] p-4 text-xs space-y-2">
          <p className="font-bold text-[#00ff41]">
            How to add these in Namecheap (4 Quick Steps):
          </p>
          <ol className="list-decimal list-inside space-y-1.5 opacity-90 leading-relaxed">
            <li>
              Log in to <strong>Namecheap.com</strong> and click <strong>Domain List</strong> in the left sidebar.
            </li>
            <li>
              Click the <strong>Manage</strong> button next to <span className="text-[#00ff41] font-semibold">{cleanDomain}</span>.
            </li>
            <li>
              Under <strong>Nameservers</strong>, make sure it is set to <strong>Namecheap BasicDNS</strong> (or Webhosting DNS).
            </li>
            <li>
              Click the <strong>Advanced DNS</strong> tab at the top, scroll to <strong>Host Records</strong>, and add each record below using <strong>Add New Record</strong>.
            </li>
          </ol>
        </div>

        {/* Copyable DNS Records Table */}
        <div className="border border-[#1a331c] bg-[#0c120c] overflow-x-auto">
          <table className="w-full text-xs text-left font-mono">
            <thead className="bg-[#0e170e] border-b border-[#1a331c] text-[11px] opacity-75">
              <tr>
                <th className="p-3 uppercase">Type</th>
                <th className="p-3 uppercase">Host</th>
                <th className="p-3 uppercase">Value (IP / Target)</th>
                <th className="p-3 uppercase">TTL</th>
                <th className="p-3 uppercase">Purpose</th>
                <th className="p-3 uppercase text-right">Copy</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#142616]">
              {dnsRecords.map((rec, i) => {
                const key = `${rec.type}-${rec.host}-${i}`;
                const isCopied = copiedKey === key;
                return (
                  <tr key={key} className="hover:bg-[#0f1b10] transition-colors">
                    <td className="p-3 font-semibold text-[#00ff41]">{rec.type}</td>
                    <td className="p-3 font-bold text-white bg-black/40 px-2 select-all">{rec.host}</td>
                    <td className="p-3 opacity-90 select-all font-mono">{rec.value}</td>
                    <td className="p-3 opacity-70">Automatic (or 1 min)</td>
                    <td className="p-3 opacity-60">{rec.note}</td>
                    <td className="p-3 text-right">
                      <button
                        onClick={() => handleCopyRecord(key, rec.value)}
                        className={`px-2.5 py-1 text-[11px] border transition-colors ${
                          isCopied
                            ? 'bg-[#00ff41] text-black border-[#00ff41] font-bold'
                            : 'border-[#1a3d1e] bg-[#142916] hover:bg-[#00ff41] hover:text-black'
                        }`}
                      >
                        {isCopied ? 'COPIED' : 'Copy Value'}
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      {/* Top Banner and Actions for Subdomain App Registry */}
      <div className="border border-[#1a331c] bg-[#0c120c] p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className={`text-base font-bold ${accentColorClass}`}>
            SUBDOMAIN ROUTING MATRIX &amp; CNAME TOPOLOGY
          </h2>
          <p className="text-xs opacity-75 mt-1 max-w-xl leading-relaxed">
            Every application operates on an isolated CNAME subdomain routed through the Vercel Edge Network,
            providing isolated deployments, zero cascade failures, and global low-latency CDN delivery.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleTestAll}
            disabled={testingAll}
            className="px-3 py-1.5 bg-[#142916] hover:bg-[#00ff41] hover:text-[#0a0a0a] transition-colors text-xs font-semibold border border-[#1a3d1e]"
          >
            {testingAll ? 'Pinging Nodes...' : 'Test All Edges'}
          </button>
          <button
            onClick={() => {
              playKeyClick();
              setShowAddModal(true);
            }}
            className="px-3 py-1.5 bg-[#00ff41] text-[#0a0a0a] text-xs font-bold hover:bg-[#52ff7d] transition-colors"
          >
            + Register Subdomain
          </button>
        </div>
      </div>

      {/* Subdomain Table */}
      <div className="border border-[#1a331c] bg-[#0c120c] overflow-x-auto">
        <table className="w-full text-xs text-left font-mono">
          <thead className="bg-[#0e170e] border-b border-[#1a331c] text-[11px] opacity-75">
            <tr>
              <th className="p-3 uppercase">Subdomain</th>
              <th className="p-3 uppercase">Application</th>
              <th className="p-3 uppercase">DNS Type</th>
              <th className="p-3 uppercase">CNAME Target</th>
              <th className="p-3 uppercase">Edge Status</th>
              <th className="p-3 uppercase">Latency</th>
              <th className="p-3 uppercase text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#142616]">
            {projects.map((project) => {
              const live = statuses[project.id];
              return (
                <tr key={project.id} className="hover:bg-[#0f1b10] transition-colors">
                  <td className="p-3 font-semibold text-[#00ff41]">
                    {project.subdomain}
                  </td>
                  <td className="p-3 opacity-90">
                    {project.name}
                  </td>
                  <td className="p-3 opacity-70">
                    CNAME
                  </td>
                  <td className="p-3 opacity-70">
                    cname.vercel-dns.com
                  </td>
                  <td className="p-3">
                    <span className="opacity-90">{live?.status || project.status}</span>
                  </td>
                  <td className="p-3 opacity-80">
                    {live?.latency || project.latency}
                  </td>
                  <td className="p-3 text-right">
                    <button
                      onClick={() => onLaunchProject(project)}
                      className="px-2.5 py-1 text-[11px] bg-[#142916] hover:bg-[#00ff41] hover:text-[#0a0a0a] border border-[#1a3d1e] transition-colors"
                    >
                      Inspect
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Add New Subdomain Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xs">
          <div className="bg-[#0b100b] border-2 border-[#1a3d1e] w-full max-w-lg p-6 font-mono space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-[#1a3d1e] pb-3">
              <h3 className="text-sm font-bold text-[#00ff41]">
                REGISTER NEW SUBDOMAIN APPLICATION
              </h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-xs opacity-70 hover:opacity-100"
              >
                &times; CANCEL
              </button>
            </div>

            <form onSubmit={handleAddSubmit} className="space-y-4 text-xs">
              <div>
                <label className="block opacity-70 mb-1">Application Name:</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. GraphViz AI"
                  value={newName}
                  onChange={(e) => {
                    setNewName(e.target.value);
                    if (!newSubdomain) {
                      setNewSubdomain(e.target.value.toLowerCase().replace(/\s+/g, '-'));
                    }
                  }}
                  className="w-full bg-[#0d170d] border border-[#1a3d1e] p-2 text-[#00ff41] outline-none"
                />
              </div>

              <div>
                <label className="block opacity-70 mb-1">Subdomain (e.g. graph.{cleanDomain}):</label>
                <input
                  type="text"
                  required
                  placeholder={`graph.${cleanDomain}`}
                  value={newSubdomain}
                  onChange={(e) => setNewSubdomain(e.target.value)}
                  className="w-full bg-[#0d170d] border border-[#1a3d1e] p-2 text-[#00ff41] outline-none"
                />
              </div>

              <div>
                <label className="block opacity-70 mb-1">Description:</label>
                <input
                  type="text"
                  placeholder="Brief application purpose and capabilities"
                  value={newDescription}
                  onChange={(e) => setNewDescription(e.target.value)}
                  className="w-full bg-[#0d170d] border border-[#1a3d1e] p-2 text-[#00ff41] outline-none"
                />
              </div>

              <div>
                <label className="block opacity-70 mb-1">Tech Stack (comma-separated):</label>
                <input
                  type="text"
                  placeholder="Astro, Tailwind, Gemini API"
                  value={newTech}
                  onChange={(e) => setNewTech(e.target.value)}
                  className="w-full bg-[#0d170d] border border-[#1a3d1e] p-2 text-[#00ff41] outline-none"
                />
              </div>

              <div>
                <label className="block opacity-70 mb-1">GitHub Repo URL:</label>
                <input
                  type="url"
                  placeholder="https://github.com/yourname/app"
                  value={newGithub}
                  onChange={(e) => setNewGithub(e.target.value)}
                  className="w-full bg-[#0d170d] border border-[#1a3d1e] p-2 text-[#00ff41] outline-none"
                />
              </div>

              <div className="pt-2 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-3 py-1.5 border border-[#1a3d1e] text-xs hover:border-[#00ff41]"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 bg-[#00ff41] text-[#0a0a0a] text-xs font-bold hover:bg-[#52ff7d]"
                >
                  Confirm &amp; Add
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
