import { FeedbackItem, FeedbackStatus } from '../types/feedback';

const VOTED_KEY = 'site_feedback_production_voted_ids';

export async function getFeedbackInventory(): Promise<FeedbackItem[]> {
  try {
    const res = await fetch('/api/feedback');
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data)) return data;
    }
  } catch (err) {
    console.error('Failed to fetch feedback from server', err);
  }
  return [];
}

export async function submitNewFeedback(
  item: Omit<FeedbackItem, 'id' | 'submittedAt' | 'upvotes' | 'status' | 'agentAnalysis'>
): Promise<FeedbackItem | null> {
  // Basic initial agent analysis heuristics based on title/description
  const text = `${item.title} ${item.description}`.toLowerCase();
  let feasibilityScore = 80;
  let estimatedComplexity: 'trivial' | 'moderate' | 'complex' = 'moderate';
  let technicalImpact: 'low' | 'medium' | 'high' = 'medium';

  if (text.includes('button') || text.includes('text') || text.includes('label') || text.includes('typo') || text.includes('link')) {
    feasibilityScore = 95;
    estimatedComplexity = 'trivial';
    technicalImpact = 'low';
  } else if (text.includes('ai') || text.includes('agent') || text.includes('realtime') || text.includes('monte carlo') || text.includes('sync')) {
    feasibilityScore = 75;
    estimatedComplexity = 'complex';
    technicalImpact = 'high';
  } else if (text.includes('filter') || text.includes('sort') || text.includes('modal') || text.includes('calendar')) {
    feasibilityScore = 90;
    estimatedComplexity = 'moderate';
    technicalImpact = 'medium';
  }

  const payload: Partial<FeedbackItem> = {
    ...item,
    feasibility: feasibilityScore >= 85 ? 'high' : feasibilityScore >= 65 ? 'medium' : 'low',
    feasibilityRationale: `Automated assessment: ${estimatedComplexity} complexity with ${technicalImpact} system impact. Ready for site owner & development staff triage.`,
    agentAnalysis: {
      feasibilityScore,
      technicalImpact,
      estimatedComplexity,
      proposedChangeSpec: `Autogenerated change intent: Review target [${item.targetPageOrComponent}] to address requested feedback: "${item.title}".`,
      automatedTestPlan: `Verify behavior changes in ${item.targetPageOrComponent} without regressions to existing components.`,
      agenticReadiness: true,
      reviewedByOwner: false,
    },
  };

  try {
    const res = await fetch('/api/feedback', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (res.ok) {
      const data = await res.json();
      window.dispatchEvent(new Event('huon_feedback_updated'));
      return data.item;
    }
  } catch (err) {
    console.error('Failed to submit feedback to server', err);
  }
  return null;
}

export async function upvoteFeedbackItem(id: string): Promise<{ success: boolean; newCount?: number }> {
  if (typeof window === 'undefined') return { success: false };
  try {
    const votedRaw = localStorage.getItem(VOTED_KEY);
    const votedList: string[] = votedRaw ? JSON.parse(votedRaw) : [];

    if (votedList.includes(id)) {
      return { success: false };
    }

    const res = await fetch(`/api/feedback/${id}/upvote`, {
      method: 'POST',
    });

    if (res.ok) {
      const data = await res.json();
      votedList.push(id);
      localStorage.setItem(VOTED_KEY, JSON.stringify(votedList));
      window.dispatchEvent(new Event('huon_feedback_updated'));
      return { success: true, newCount: data.newCount };
    }
  } catch (err) {
    console.error('Error upvoting feedback item', err);
  }
  return { success: false };
}

export function hasUserVoted(id: string): boolean {
  if (typeof window === 'undefined') return false;
  try {
    const votedRaw = localStorage.getItem(VOTED_KEY);
    const votedList: string[] = votedRaw ? JSON.parse(votedRaw) : [];
    return votedList.includes(id);
  } catch {
    return false;
  }
}

export async function updateFeedbackStatusByOwner(
  id: string,
  status: FeedbackStatus,
  ownerNotes?: string,
  deployedCommit?: string
): Promise<FeedbackItem | null> {
  try {
    const res = await fetch(`/api/feedback/${id}/status`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status, ownerNotes, deployedCommit }),
    });
    if (res.ok) {
      const data = await res.json();
      window.dispatchEvent(new Event('huon_feedback_updated'));
      return data.item;
    }
  } catch (err) {
    console.error('Error updating feedback status', err);
  }
  return null;
}
