import { FeedbackItem, FeedbackStatus } from '../types/feedback';
import { INITIAL_FEEDBACK_ITEMS } from '../data/initialFeedback';

const STORAGE_KEY = 'site_feedback_production_inventory_v2';
const VOTED_KEY = 'site_feedback_production_voted_ids';

export function getFeedbackInventory(): FeedbackItem[] {
  if (typeof window === 'undefined') return INITIAL_FEEDBACK_ITEMS;
  try {
    // If old mock v1 storage exists, clean it up
    if (localStorage.getItem('huon_feedback_inventory_v1')) {
      localStorage.removeItem('huon_feedback_inventory_v1');
    }
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(INITIAL_FEEDBACK_ITEMS));
      return INITIAL_FEEDBACK_ITEMS;
    }
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(INITIAL_FEEDBACK_ITEMS));
      return INITIAL_FEEDBACK_ITEMS;
    }
    return parsed;
  } catch (err) {
    console.error('Failed to parse feedback inventory from localStorage', err);
    return INITIAL_FEEDBACK_ITEMS;
  }
}

export function saveFeedbackInventory(items: FeedbackItem[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
    window.dispatchEvent(new Event('huon_feedback_updated'));
  } catch (err) {
    console.error('Failed to save feedback inventory', err);
  }
}

export function submitNewFeedback(item: Omit<FeedbackItem, 'id' | 'submittedAt' | 'upvotes' | 'status' | 'agentAnalysis'>): FeedbackItem {
  const current = getFeedbackInventory();

  // Basic initial agent analysis heuristics based on title/description
  const text = `${item.title} ${item.description}`.toLowerCase();
  let feasibilityScore = 80;
  let estimatedComplexity: 'trivial' | 'moderate' | 'complex' = 'moderate';
  let technicalImpact: 'low' | 'medium' | 'high' = 'medium';

  if (text.includes('button') || text.includes('text') || text.includes('label') || text.includes('typo') || text.includes('link')) {
    feasibilityScore = 95;
    estimatedComplexity = 'trivial';
    technicalImpact = 'low';
  } else if (text.includes('ai') || text.includes('agent') || text.includes('realtime') || text.includes('monte carlo') || text.includes('sync')) {
    feasibilityScore = 75;
    estimatedComplexity = 'complex';
    technicalImpact = 'high';
  } else if (text.includes('filter') || text.includes('sort') || text.includes('modal') || text.includes('calendar')) {
    feasibilityScore = 90;
    estimatedComplexity = 'moderate';
    technicalImpact = 'medium';
  }

  const newItem: FeedbackItem = {
    ...item,
    id: `fb-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6)}`,
    submittedAt: new Date().toISOString(),
    upvotes: 1,
    status: 'submitted',
    feasibility: feasibilityScore >= 85 ? 'high' : feasibilityScore >= 65 ? 'medium' : 'low',
    feasibilityRationale: `Automated assessment: ${estimatedComplexity} complexity with ${technicalImpact} system impact. Ready for owner triage.`,
    agentAnalysis: {
      feasibilityScore,
      technicalImpact,
      estimatedComplexity,
      proposedChangeSpec: `Autogenerated change intent: Review target [${item.targetPageOrComponent}] to address requested feedback: "${item.title}".`,
      automatedTestPlan: `Verify behavior changes in ${item.targetPageOrComponent} without regressions to existing components.`,
      agenticReadiness: true,
      reviewedByOwner: false,
    },
  };

  const updated = [newItem, ...current];
  saveFeedbackInventory(updated);
  return newItem;
}

export function upvoteFeedbackItem(id: string): { success: boolean; newCount?: number } {
  if (typeof window === 'undefined') return { success: false };
  try {
    const votedRaw = localStorage.getItem(VOTED_KEY);
    const votedList: string[] = votedRaw ? JSON.parse(votedRaw) : [];

    if (votedList.includes(id)) {
      return { success: false }; // Already voted
    }

    const current = getFeedbackInventory();
    let newCount = 0;
    const updated = current.map((item) => {
      if (item.id === id) {
        newCount = item.upvotes + 1;
        return { ...item, upvotes: newCount };
      }
      return item;
    });

    saveFeedbackInventory(updated);
    votedList.push(id);
    localStorage.setItem(VOTED_KEY, JSON.stringify(votedList));
    return { success: true, newCount };
  } catch (err) {
    console.error('Error upvoting feedback item', err);
    return { success: false };
  }
}

export function hasUserVoted(id: string): boolean {
  if (typeof window === 'undefined') return false;
  try {
    const votedRaw = localStorage.getItem(VOTED_KEY);
    const votedList: string[] = votedRaw ? JSON.parse(votedRaw) : [];
    return votedList.includes(id);
  } catch {
    return false;
  }
}

export function updateFeedbackStatusByOwner(
  id: string,
  status: FeedbackStatus,
  ownerNotes?: string,
  deployedCommit?: string
): FeedbackItem | null {
  const current = getFeedbackInventory();
  let updatedItem: FeedbackItem | null = null;

  const updated = current.map((item) => {
    if (item.id === id) {
      const isDeploying = status === 'deployed';
      updatedItem = {
        ...item,
        status,
        deployedAt: isDeploying ? item.deployedAt || new Date().toISOString() : item.deployedAt,
        agentAnalysis: {
          ...item.agentAnalysis,
          reviewedByOwner: true,
          ownerNotes: ownerNotes !== undefined ? ownerNotes : item.agentAnalysis.ownerNotes,
          deployedCommit: deployedCommit !== undefined ? deployedCommit : item.agentAnalysis.deployedCommit,
        },
      };
      return updatedItem;
    }
    return item;
  });

  if (updatedItem) {
    saveFeedbackInventory(updated);
  }
  return updatedItem;
}

export function resetFeedbackToDefault(): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(INITIAL_FEEDBACK_ITEMS));
  localStorage.removeItem(VOTED_KEY);
  window.dispatchEvent(new Event('huon_feedback_updated'));
}
